"""
Fix Prompt Builder

Compiles all scan findings into a single, structured Markdown artifact
designed to be pasted directly into any AI coding agent (Claude Code,
Cursor, Windsurf, Copilot Workspace, etc.) for automated remediation.

Key requirements:
- Findings grouped by file to minimize context-switching for the agent.
- Exact file paths and line ranges included for each finding.
- Secret values are NEVER included verbatim — middle is always redacted.
- Auto-chunked into multiple numbered files if the prompt would be too large.
- Written to .remy/ in the project directory (or cwd as fallback).
"""

import json
import re
from collections import defaultdict
from datetime import datetime
from pathlib import Path
from typing import Optional

from .models import ScanReport, Finding, Severity

# Maximum characters per prompt chunk (~30k chars ≈ ~8k tokens, comfortable for most agents)
MAX_CHUNK_CHARS = 30_000

# Output directory relative to cwd
OUTPUT_DIR = Path(".remy")

# Severity display labels
SEV_LABELS = {
    Severity.CRITICAL: "CRITICAL",
    Severity.HIGH:     "HIGH",
    Severity.MEDIUM:   "MEDIUM",
    Severity.LOW:      "LOW",
    Severity.INFO:     "INFO",
}


def _redact_secret(text: str) -> str:
    """Redact potential secret values in text, showing only first/last 4 chars."""
    # Redact long high-entropy-looking tokens in code snippets
    def _redact_match(m: re.Match) -> str:
        val = m.group(0)
        if len(val) <= 8:
            return "****"
        return val[:4] + "***" + val[-4:]

    # Redact string literals that look like secrets (≥20 chars, alphanumeric+symbols)
    return re.sub(
        r"""(?<=['"])[A-Za-z0-9+/=_\-]{20,}(?=['"])""",
        _redact_match,
        text,
    )


def _format_finding(finding: Finding, index: int) -> str:
    """Format a single finding into Markdown."""
    sev_label = SEV_LABELS[finding.severity]
    lines = []
    lines.append(f"### [{sev_label}] {finding.title}")
    lines.append(f"**File:** `{finding.file}`, lines {finding.line_start}–{finding.line_end}  ")
    if finding.cwe:
        lines.append(f"**CWE:** {finding.cwe}  ")
    lines.append(f"**Scanner:** {finding.scanner}  ")
    lines.append(f"**Confidence:** {int(finding.confidence * 100)}%")
    lines.append("")
    lines.append(f"**Issue:** {finding.description}")
    lines.append("")
    lines.append(f"**Fix instructions:** {finding.remediation_hint}")

    if finding.code_snippet:
        safe_snippet = _redact_secret(finding.code_snippet)
        lines.append("")
        lines.append("```")
        lines.append(safe_snippet)
        lines.append("```")

    lines.append("")
    return "\n".join(lines)


def _build_header(report: ScanReport, chunk_num: Optional[int] = None, total_chunks: Optional[int] = None) -> str:
    """Build the standard Fix Prompt header."""
    chunk_info = ""
    if chunk_num is not None and total_chunks is not None and total_chunks > 1:
        chunk_info = f" (Part {chunk_num} of {total_chunks})"

    lines = [
        "# Remy Security & Bug Fix Prompt" + chunk_info,
        "",
        "Generated by **Remy Agent** (Medusa Security) — https://github.com/Medusa-Security  ",
        f"Scan ID: `{report.scan_id}` · {report.timestamp.strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "---",
        "",
        "You are an AI coding agent. Fix the following issues in this codebase.",
        "Apply minimal, targeted changes. Preserve existing behavior and style.",
        "After each fix, briefly note what was changed and why.",
        "",
        "---",
        "",
    ]
    return "\n".join(lines)


def _build_summary(report: ScanReport) -> str:
    """Build the summary section."""
    lines = [
        "## Summary",
        "",
        f"- **{report.critical_count} Critical**, {report.high_count} High, "
        f"{report.medium_count} Medium, {report.low_count} Low, {report.info_count} Info "
        f"findings across {len(report.findings_by_file())} file(s)",
        f"- Scanned {report.files_scanned} files in {report.duration_seconds:.2f}s",
        f"- Scanners run: {', '.join(report.scanners_used)}",
        "",
    ]
    return "\n".join(lines)


def _build_checklist(report: ScanReport) -> str:
    """Build a dynamic verification checklist based on what was actually found."""
    from .models import Severity

    # Collect which scanner types produced findings
    scanners = {f.scanner for f in report.findings}
    cwes = {f.cwe for f in report.findings if f.cwe}

    items: list[str] = []

    # Always include — tests should always run
    items.append("- [ ] All tests pass after changes are applied")

    if "secrets" in scanners or "CWE-798" in cwes:
        items.append("- [ ] All hardcoded secrets moved to environment variables or a secrets manager")
        items.append("- [ ] Exposed API keys and tokens rotated in their respective dashboards")

    if "api_surface" in scanners or "CWE-306" in cwes or "CWE-770" in cwes:
        items.append("- [ ] All non-public endpoints require authentication")
        items.append("- [ ] Rate limiting applied to auth, password-reset, upload, and webhook endpoints")

    if "auth_bypass" in scanners or "CWE-347" in cwes or "CWE-639" in cwes:
        items.append("- [ ] JWT verification enabled with a strong algorithm (no algorithm=none)")
        items.append("- [ ] Authorization decisions made server-side, not from request parameters")
        items.append("- [ ] Object ownership verified before returning data (IDOR prevention)")

    if "sast_python" in scanners or "CWE-89" in cwes:
        items.append("- [ ] SQL queries use parameterized statements (no string formatting or f-strings)")

    if "sast_python" in scanners or "CWE-78" in cwes:
        items.append("- [ ] No eval() / exec() with dynamic or user-supplied input")
        items.append("- [ ] subprocess calls use shell=False with argument lists")

    if "sast_python" in scanners or "CWE-502" in cwes:
        items.append("- [ ] Deserialization only from trusted, validated sources (no pickle on user data)")

    if "dependency" in scanners or "CWE-1035" in cwes:
        items.append("- [ ] Dependencies upgraded to patched versions where flagged")

    if "sast_js_ts" in scanners or "CWE-79" in cwes:
        items.append("- [ ] User input is sanitized before rendering as HTML (XSS prevention)")

    lines = [
        "---",
        "",
        "## Verification Checklist",
        "",
        "After applying all fixes, verify:",
        "",
        *items,
        "",
        "---",
        "*Fix prompt generated by [Remy Agent](https://github.com/Medusa-Security) — "
        "Built by Medusa Security*",
        "",
    ]
    return "\n".join(lines)


def build_fix_prompt(report: ScanReport) -> list[str]:
    """Compile all findings into one or more Fix Prompt strings.

    Findings are grouped by file, ordered by severity. If the total
    content exceeds MAX_CHUNK_CHARS, it is split into numbered chunks.

    Args:
        report: The ScanReport produced by the orchestrator.

    Returns:
        List of prompt strings (usually one, more if chunked).
    """
    if not report.findings:
        return []

    # Group findings by file, sorted by severity within each file
    grouped = report.findings_by_file()

    # Build the findings section
    findings_blocks: list[str] = ["## Findings\n\n"]
    index = 1
    for file_path in sorted(grouped.keys()):
        findings_in_file = grouped[file_path]
        findings_blocks.append(f"---\n\n### 📄 `{file_path}`\n\n")
        for finding in findings_in_file:
            findings_blocks.append(_format_finding(finding, index))
            index += 1

    header = _build_header(report)
    summary = _build_summary(report)
    checklist = _build_checklist(report)

    # Combine and check if chunking is needed
    full_content = header + summary + "".join(findings_blocks) + checklist

    if len(full_content) <= MAX_CHUNK_CHARS:
        return [full_content]

    # ── Chunking ──────────────────────────────────────────────────────────────
    # Split findings_blocks into chunks by character budget
    chunks_content: list[list[str]] = [[]]
    current_size = 0
    base_overhead = len(header) + len(summary) + len(checklist) + 500  # buffer

    for block in findings_blocks:
        if current_size + len(block) + base_overhead > MAX_CHUNK_CHARS and current_size > 0:
            chunks_content.append([])
            current_size = 0
        chunks_content[-1].append(block)
        current_size += len(block)

    total_chunks = len(chunks_content)
    prompt_strings: list[str] = []

    for i, chunk_blocks in enumerate(chunks_content, 1):
        chunk_header = _build_header(report, chunk_num=i, total_chunks=total_chunks)
        chunk_summary = summary if i == 1 else (
            f"## Summary\n\n*(Continued from part {i - 1} of {total_chunks})*\n\n"
        )
        chunk_body = chunk_header + chunk_summary + "".join(chunk_blocks)
        if i == total_chunks:
            chunk_body += _build_checklist(report)
        else:
            chunk_body += (
                f"\n---\n\n*Continued in Fix Prompt Part {i + 1} of {total_chunks}*\n"
            )
        prompt_strings.append(chunk_body)

    return prompt_strings


def save_prompt(report: ScanReport, output_dir: Optional[Path] = None) -> list[str]:
    """Build and save Fix Prompt files, returning paths of written files.

    Writes to .remy/fix_prompt.md (or fix_prompt_1.md, fix_prompt_2.md if chunked).

    Args:
        report: The ScanReport to generate prompts from.
        output_dir: Override output directory (defaults to .remy in cwd).

    Returns:
        List of absolute path strings for the written files.
    """
    prompts = build_fix_prompt(report)
    if not prompts:
        return []

    out_dir = output_dir or OUTPUT_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    written: list[str] = []
    # Always use numbered names for consistency regardless of chunk count
    for i, content in enumerate(prompts, 1):
        p = out_dir / f"fix_prompt_{i}.md"
        p.write_text(content, encoding="utf-8")
        written.append(str(p))

    return written


def build_fix_prompt_from_cache(cache_file: Path) -> list[str]:
    """Rebuild Fix Prompt strings from a cached scan JSON file.

    Args:
        cache_file: Path to the last_scan.json cache file.

    Returns:
        List of prompt strings.
    """
    report = _load_report_from_cache(cache_file)
    if report is None:
        return []
    return build_fix_prompt(report)


def save_prompt_from_cache(cache_file: Path, output_dir: Optional[Path] = None) -> list[str]:
    """Load cached findings and write Fix Prompt files.

    Args:
        cache_file: Path to the last_scan.json cache file.
        output_dir: Override output directory.

    Returns:
        List of written file paths.
    """
    report = _load_report_from_cache(cache_file)
    if report is None:
        return []
    return save_prompt(report, output_dir=output_dir)


def _load_report_from_cache(cache_file: Path) -> Optional[ScanReport]:
    """Deserialize a ScanReport from the cached JSON file.

    Args:
        cache_file: Path to the JSON cache file.

    Returns:
        Reconstructed ScanReport, or None if deserialization fails.
    """
    try:
        data = json.loads(cache_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None

    try:
        findings = []
        for f in data.get("findings", []):
            findings.append(
                Finding(
                    id=f["id"],
                    scanner=f["scanner"],
                    severity=Severity(f["severity"]),
                    cwe=f.get("cwe"),
                    file=f["file"],
                    line_start=f["line_start"],
                    line_end=f["line_end"],
                    title=f["title"],
                    description=f["description"],
                    remediation_hint=f["remediation_hint"],
                    confidence=f.get("confidence", 0.5),
                    code_snippet=f.get("code_snippet"),
                )
            )

        return ScanReport(
            scan_id=data.get("scan_id", "cached"),
            target_path=data.get("target_path", "."),
            timestamp=datetime.fromisoformat(data.get("timestamp", datetime.now().isoformat())),
            findings=findings,
            files_scanned=data.get("files_scanned", 0),
            duration_seconds=data.get("duration_seconds", 0.0),
            scanners_used=data.get("scanners_used", []),
        )
    except (KeyError, ValueError, TypeError):
        return None
