"""Tests for the DependencyScanner and lockfile parsers."""

from pathlib import Path
from unittest.mock import AsyncMock, patch, MagicMock
import pytest

from remy.scanners.dependency_scanner import (
    DependencyScanner,
    _parse_package_lock_json,
    _parse_poetry_lock,
    _parse_uv_lock,
    _parse_pipfile_lock,
    _parse_yarn_lock,
    _parse_go_sum,
)
from remy.report.models import Severity


@pytest.fixture
def scanner():
    return DependencyScanner()


class TestLockfileParsers:
    def test_parse_package_lock_json(self):
        content = """{
          "name": "myapp",
          "version": "1.0.0",
          "packages": {
            "": {
              "name": "myapp",
              "version": "1.0.0"
            },
            "node_modules/express": {
              "version": "4.17.1",
              "resolved": "https://registry.npmjs.org/express/-/express-4.17.1.tgz"
            },
            "node_modules/lodash": {
              "version": "4.17.21"
            }
          }
        }"""
        deps = _parse_package_lock_json(content)
        pkgs = {pkg: ver for pkg, ver, _ in deps}
        assert "express" in pkgs
        assert pkgs["express"] == "4.17.1"
        assert "lodash" in pkgs
        assert pkgs["lodash"] == "4.17.21"

    def test_parse_poetry_lock(self):
        content = """[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."

[[package]]
name = "urllib3"
version = "2.0.7"
"""
        deps = _parse_poetry_lock(content)
        pkgs = {pkg: ver for pkg, ver, _ in deps}
        assert pkgs["requests"] == "2.31.0"
        assert pkgs["urllib3"] == "2.0.7"

    def test_parse_uv_lock(self):
        content = """[[package]]
name = "fastapi"
version = "0.109.2"
"""
        deps = _parse_uv_lock(content)
        assert len(deps) == 1
        assert deps[0][0] == "fastapi"
        assert deps[0][1] == "0.109.2"

    def test_parse_pipfile_lock(self):
        content = """{
          "_meta": {},
          "default": {
            "django": {
              "version": "==4.2.8"
            }
          },
          "develop": {
            "pytest": {
              "version": "==7.4.3"
            }
          }
        }"""
        deps = _parse_pipfile_lock(content)
        pkgs = {pkg: ver for pkg, ver, _ in deps}
        assert pkgs["django"] == "4.2.8"
        assert pkgs["pytest"] == "7.4.3"

    def test_parse_yarn_lock(self):
        content = """# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

express@^4.17.1:
  version "4.17.1"
  resolved "https://registry.yarnpkg.com/express/-/express-4.17.1.tgz"
"""
        deps = _parse_yarn_lock(content)
        assert len(deps) == 1
        assert deps[0][0] == "express"
        assert deps[0][1] == "4.17.1"

    def test_parse_go_sum(self):
        content = """github.com/gin-gonic/gin v1.9.1 h1:4ijdn...
github.com/gin-gonic/gin v1.9.1/go.mod h1:...
"""
        deps = _parse_go_sum(content)
        assert len(deps) == 1
        assert deps[0][0] == "github.com/gin-gonic/gin"
        assert deps[0][1] == "1.9.1"


class TestDependencyScannerAsync:
    @pytest.mark.asyncio
    async def test_scan_file_with_mocked_querybatch(self, scanner):
        content = "requests==2.19.0\nurllib3==1.24.1"

        mock_response = MagicMock()
        mock_response.status_code = 200
        mock_response.json.return_value = {
            "results": [
                {
                    "vulns": [
                        {
                            "id": "CVE-2018-18074",
                            "summary": "Requests vuln",
                            "severity": [{"score": "7.5"}],
                            "affected": [
                                {"ranges": [{"events": [{"fixed": "2.20.0"}]}]}
                            ],
                        }
                    ]
                },
                {"vulns": []},
            ]
        }

        mock_client = AsyncMock()
        mock_client.post.return_value = mock_response

        with patch("httpx.AsyncClient", return_value=mock_client):
            mock_client.__aenter__.return_value = mock_client
            findings = await scanner.scan_file(
                Path("requirements.txt"), content, "python"
            )

        assert len(findings) == 1
        assert "requests" in findings[0].title
        assert "CVE-2018-18074" in findings[0].title
        assert findings[0].severity == Severity.HIGH
